/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JOptionPane;
import model.CheckingAccount;

/**
 *
 * @author 12013
 */
public class CreateCheckingAccPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreatePerInfo
     */
    CheckingAccount checking;
    
    public CreateCheckingAccPanel(CheckingAccount checking) {
        initComponents();
        this.checking = checking;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        txtChkRtNo = new javax.swing.JTextField();
        txtChkBaName = new javax.swing.JTextField();
        txtChkAccBal = new javax.swing.JTextField();
        txtChkAccNo = new javax.swing.JTextField();
        txtSavChkType = new javax.swing.JTextField();
        btnSaveCheckAcc = new javax.swing.JButton();
        lblSavRtNo = new javax.swing.JLabel();
        lblSavAccNo = new javax.swing.JLabel();
        lnlSavBaName = new javax.swing.JLabel();
        lblSavAccBal = new javax.swing.JLabel();
        lblSAccType = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 204));
        setPreferredSize(new java.awt.Dimension(818, 537));

        lblTitle.setBackground(new java.awt.Color(255, 204, 204));
        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Enter Checking Account Details");

        txtChkRtNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChkRtNoActionPerformed(evt);
            }
        });

        txtSavChkType.setEditable(false);
        txtSavChkType.setText("Checking");
        txtSavChkType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSavChkTypeActionPerformed(evt);
            }
        });

        btnSaveCheckAcc.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSaveCheckAcc.setText("Save");
        btnSaveCheckAcc.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        btnSaveCheckAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveCheckAccActionPerformed(evt);
            }
        });

        lblSavRtNo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSavRtNo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblSavRtNo.setText("Bank Routing Number :");

        lblSavAccNo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSavAccNo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblSavAccNo.setText("Bank Account Number :");

        lnlSavBaName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lnlSavBaName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lnlSavBaName.setText("Bank Name :");

        lblSavAccBal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSavAccBal.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblSavAccBal.setText("Account Balance :");

        lblSAccType.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSAccType.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblSAccType.setText("Account Type :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(172, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lnlSavBaName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSavAccBal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSAccType, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSavRtNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSavAccNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtChkAccBal, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtChkAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtChkRtNo, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtChkBaName, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSavChkType, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(172, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSaveCheckAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtChkAccBal, txtChkAccNo, txtChkBaName, txtChkRtNo, txtSavChkType});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblSAccType, lblSavAccBal, lnlSavBaName});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lnlSavBaName, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtChkBaName, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSavRtNo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtChkRtNo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSavAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtChkAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSavAccBal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtChkAccBal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSAccType, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSavChkType, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btnSaveCheckAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(154, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtChkAccBal, txtChkAccNo, txtChkBaName, txtChkRtNo, txtSavChkType});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblSAccType, lblSavAccBal, lblSavAccNo, lblSavRtNo, lnlSavBaName});

    }// </editor-fold>//GEN-END:initComponents

    private void txtChkRtNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChkRtNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChkRtNoActionPerformed

    private void btnSaveCheckAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveCheckAccActionPerformed
        // TODO add your handling code here:
        
       checking.setChkBankName(txtChkBaName.getText());
       checking.setChkBankRtNo(txtChkRtNo.getText());
       checking.setChkBankAcNo(txtChkAccNo.getText());
       checking.setChkAccBal(txtChkAccBal.getText());
       
       
        
        
        JOptionPane.showMessageDialog(this, "Checking Account Information has been saved.");
        
    }//GEN-LAST:event_btnSaveCheckAccActionPerformed

    private void txtSavChkTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSavChkTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSavChkTypeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveCheckAcc;
    private javax.swing.JLabel lblSAccType;
    private javax.swing.JLabel lblSavAccBal;
    private javax.swing.JLabel lblSavAccNo;
    private javax.swing.JLabel lblSavRtNo;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lnlSavBaName;
    private javax.swing.JTextField txtChkAccBal;
    private javax.swing.JTextField txtChkAccNo;
    private javax.swing.JTextField txtChkBaName;
    private javax.swing.JTextField txtChkRtNo;
    private javax.swing.JTextField txtSavChkType;
    // End of variables declaration//GEN-END:variables
}
