/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JOptionPane;
import model.SavingsAccount;

/**
 *
 * @author 12013
 */
public class CreateSavingAccPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreatePerInfo
     */
    SavingsAccount savings;
    
    public CreateSavingAccPanel(SavingsAccount savings) {
        initComponents();
        this.savings = savings;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        txtSavRtNo = new javax.swing.JTextField();
        txtSavBaName = new javax.swing.JTextField();
        txtSavAccBal = new javax.swing.JTextField();
        txtSavAccNo = new javax.swing.JTextField();
        txtSavAccType = new javax.swing.JTextField();
        btnSaveSavAcc = new javax.swing.JButton();
        lblSavRtNo = new javax.swing.JLabel();
        lblSavAccNo = new javax.swing.JLabel();
        lnlSavBaName = new javax.swing.JLabel();
        lblSavAccBal = new javax.swing.JLabel();
        lblSAccType = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));
        setPreferredSize(new java.awt.Dimension(818, 537));

        lblTitle.setBackground(new java.awt.Color(255, 204, 204));
        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Enter Savings Account Details");

        txtSavRtNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSavRtNoActionPerformed(evt);
            }
        });

        txtSavAccType.setEditable(false);
        txtSavAccType.setText("Savings");
        txtSavAccType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSavAccTypeActionPerformed(evt);
            }
        });

        btnSaveSavAcc.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSaveSavAcc.setText("Save");
        btnSaveSavAcc.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        btnSaveSavAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveSavAccActionPerformed(evt);
            }
        });

        lblSavRtNo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSavRtNo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblSavRtNo.setText("Bank Routing Number :");

        lblSavAccNo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSavAccNo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblSavAccNo.setText("Bank Account Number :");

        lnlSavBaName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lnlSavBaName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lnlSavBaName.setText("Bank Name :");

        lblSavAccBal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSavAccBal.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblSavAccBal.setText("Account Balance :");

        lblSAccType.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSAccType.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblSAccType.setText("Account Type :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(172, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lnlSavBaName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSavAccBal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSAccType, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSavRtNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSavAccNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSavAccBal, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSavAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSavRtNo, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSavBaName, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSavAccType, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(172, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSaveSavAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtSavAccBal, txtSavAccNo, txtSavAccType, txtSavBaName, txtSavRtNo});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblSAccType, lblSavAccBal, lnlSavBaName});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lnlSavBaName, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSavBaName, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSavRtNo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSavRtNo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSavAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSavAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSavAccBal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSavAccBal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSAccType, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSavAccType, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSaveSavAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtSavAccBal, txtSavAccNo, txtSavAccType, txtSavBaName, txtSavRtNo});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblSAccType, lblSavAccBal, lblSavAccNo, lblSavRtNo, lnlSavBaName});

    }// </editor-fold>//GEN-END:initComponents

    private void txtSavRtNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSavRtNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSavRtNoActionPerformed

    private void btnSaveSavAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveSavAccActionPerformed
        // TODO add your handling code here:
        
        savings.setBankName(txtSavBaName.getText());
        savings.setBankRtNo(txtSavRtNo.getText());
        savings.setBankAcNo(txtSavAccNo.getText());
        savings.setAccBal(txtSavAccBal.getText());
       
        
        
        JOptionPane.showMessageDialog(this, "Savings Account Information has been saved.");
        
    }//GEN-LAST:event_btnSaveSavAccActionPerformed

    private void txtSavAccTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSavAccTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSavAccTypeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveSavAcc;
    private javax.swing.JLabel lblSAccType;
    private javax.swing.JLabel lblSavAccBal;
    private javax.swing.JLabel lblSavAccNo;
    private javax.swing.JLabel lblSavRtNo;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lnlSavBaName;
    private javax.swing.JTextField txtSavAccBal;
    private javax.swing.JTextField txtSavAccNo;
    private javax.swing.JTextField txtSavAccType;
    private javax.swing.JTextField txtSavBaName;
    private javax.swing.JTextField txtSavRtNo;
    // End of variables declaration//GEN-END:variables
}
