/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.Address;
import model.CheckingAccount;
import model.License;
import model.MedicalRec;
import model.PersonalInfo;
import model.SavingsAccount;
import model.Report;


/**
 *
 * @author 12013
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    
    PersonalInfo person;
    Address address;
    SavingsAccount savings;
    CheckingAccount checking;
    License license;
    MedicalRec record;
    Report report;
    
    public MainJFrame() {
        initComponents();
        
        person = new PersonalInfo();
        address = new Address();
        savings = new SavingsAccount();
        checking = new CheckingAccount();
        license = new License();
        record = new MedicalRec();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        controlPanel = new javax.swing.JPanel();
        btnCreatePI = new javax.swing.JButton();
        btnViewPI = new javax.swing.JButton();
        btnViewSavAcc = new javax.swing.JButton();
        btnCreateSavAcc = new javax.swing.JButton();
        btnCreateAdd = new javax.swing.JButton();
        btnCreateCheckAcc = new javax.swing.JButton();
        btnViewCheckAcc = new javax.swing.JButton();
        btnViewAdd = new javax.swing.JButton();
        btnViewLic = new javax.swing.JButton();
        btnCreateLic = new javax.swing.JButton();
        btnViewReport = new javax.swing.JButton();
        btnCreateMedRec = new javax.swing.JButton();
        btnViewMedRec = new javax.swing.JButton();
        viewPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Assignment 1");
        setBackground(new java.awt.Color(255, 204, 204));

        splitPane.setBackground(new java.awt.Color(255, 153, 153));
        splitPane.setDividerLocation(150);
        splitPane.setDividerSize(10);
        splitPane.setForeground(new java.awt.Color(255, 51, 153));

        controlPanel.setBackground(new java.awt.Color(255, 204, 255));

        btnCreatePI.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnCreatePI.setForeground(new java.awt.Color(0, 0, 153));
        btnCreatePI.setText("Personal Information");
        btnCreatePI.setToolTipText("Click to Enter Personal Details");
        btnCreatePI.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.lightGray, null, null));
        btnCreatePI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatePIActionPerformed(evt);
            }
        });

        btnViewPI.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnViewPI.setForeground(new java.awt.Color(0, 0, 153));
        btnViewPI.setText("View Personal Info");
        btnViewPI.setToolTipText("Click to View Personal Details");
        btnViewPI.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.lightGray, null, null));
        btnViewPI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPIActionPerformed(evt);
            }
        });

        btnViewSavAcc.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnViewSavAcc.setForeground(new java.awt.Color(51, 102, 255));
        btnViewSavAcc.setText("View Account Details");
        btnViewSavAcc.setToolTipText("Click to View Saving Account Details");
        btnViewSavAcc.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.lightGray, null, null));
        btnViewSavAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewSavAccActionPerformed(evt);
            }
        });

        btnCreateSavAcc.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnCreateSavAcc.setForeground(new java.awt.Color(51, 102, 255));
        btnCreateSavAcc.setText("Savings Account");
        btnCreateSavAcc.setToolTipText("Click to Enter Saving Account Details");
        btnCreateSavAcc.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.lightGray, null, null));
        btnCreateSavAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateSavAccActionPerformed(evt);
            }
        });

        btnCreateAdd.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnCreateAdd.setForeground(new java.awt.Color(51, 102, 0));
        btnCreateAdd.setText("Address");
        btnCreateAdd.setToolTipText("Click to Enter Address Details");
        btnCreateAdd.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.lightGray, null, null));
        btnCreateAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAddActionPerformed(evt);
            }
        });

        btnCreateCheckAcc.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnCreateCheckAcc.setForeground(new java.awt.Color(102, 102, 0));
        btnCreateCheckAcc.setText("Checking Account");
        btnCreateCheckAcc.setToolTipText("Click to Enter Checking Account Details");
        btnCreateCheckAcc.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.lightGray, null, null));
        btnCreateCheckAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateCheckAccActionPerformed(evt);
            }
        });

        btnViewCheckAcc.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnViewCheckAcc.setForeground(new java.awt.Color(102, 102, 0));
        btnViewCheckAcc.setText("View Account Details");
        btnViewCheckAcc.setToolTipText("Click to View Checking Account Details");
        btnViewCheckAcc.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.lightGray, null, null));
        btnViewCheckAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCheckAccActionPerformed(evt);
            }
        });

        btnViewAdd.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnViewAdd.setForeground(new java.awt.Color(51, 102, 0));
        btnViewAdd.setText("View Address");
        btnViewAdd.setToolTipText("Click to View Address Details");
        btnViewAdd.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.lightGray, null, null));
        btnViewAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAddActionPerformed(evt);
            }
        });

        btnViewLic.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnViewLic.setForeground(new java.awt.Color(153, 0, 153));
        btnViewLic.setText("View License");
        btnViewLic.setToolTipText("Click to View Driver's License Details");
        btnViewLic.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.lightGray, null, null));
        btnViewLic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewLicActionPerformed(evt);
            }
        });

        btnCreateLic.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnCreateLic.setForeground(new java.awt.Color(153, 0, 153));
        btnCreateLic.setText("License");
        btnCreateLic.setToolTipText("Click to Enter Driver's License Details");
        btnCreateLic.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.lightGray, null, null));
        btnCreateLic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateLicActionPerformed(evt);
            }
        });

        btnViewReport.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnViewReport.setText("REPORT");
        btnViewReport.setToolTipText("Click to view the Report");
        btnViewReport.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.lightGray, null, null));
        btnViewReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewReportActionPerformed(evt);
            }
        });

        btnCreateMedRec.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnCreateMedRec.setForeground(new java.awt.Color(0, 51, 51));
        btnCreateMedRec.setText("Medical Record");
        btnCreateMedRec.setToolTipText("Click to Enter Medical Record");
        btnCreateMedRec.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.lightGray, null, null));
        btnCreateMedRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateMedRecActionPerformed(evt);
            }
        });

        btnViewMedRec.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnViewMedRec.setForeground(new java.awt.Color(0, 51, 51));
        btnViewMedRec.setText("View Record");
        btnViewMedRec.setToolTipText("Click to View Medical Record");
        btnViewMedRec.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.lightGray, null, null));
        btnViewMedRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewMedRecActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCreatePI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewPI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(btnViewSavAcc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCreateSavAcc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCreateCheckAcc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewCheckAcc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewLic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCreateLic, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCreateMedRec, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCreateAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewMedRec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(controlPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnViewAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnCreatePI, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewPI, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCreateAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(btnCreateSavAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewSavAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCreateCheckAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewCheckAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCreateLic, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewLic, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCreateMedRec, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewMedRec, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(btnViewReport, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(controlPanelLayout.createSequentialGroup()
                    .addGap(154, 154, 154)
                    .addComponent(btnViewAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(481, Short.MAX_VALUE)))
        );

        splitPane.setLeftComponent(controlPanel);

        viewPanel.setBackground(new java.awt.Color(204, 255, 204));
        viewPanel.setAutoscrolls(true);

        javax.swing.GroupLayout viewPanelLayout = new javax.swing.GroupLayout(viewPanel);
        viewPanel.setLayout(viewPanelLayout);
        viewPanelLayout.setHorizontalGroup(
            viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 797, Short.MAX_VALUE)
        );
        viewPanelLayout.setVerticalGroup(
            viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        splitPane.setRightComponent(viewPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreatePIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatePIActionPerformed
        // TODO add your handling code here:
        CreatePerInfoPanel createpipanel = new CreatePerInfoPanel(person);
        splitPane.setRightComponent(createpipanel);
        
    }//GEN-LAST:event_btnCreatePIActionPerformed

    private void btnViewPIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPIActionPerformed
        // TODO add your handling code here:
        
        ViewPerInfoPanel viewpipanel = new ViewPerInfoPanel(person);
        splitPane.setRightComponent(viewpipanel);
        
       
    }//GEN-LAST:event_btnViewPIActionPerformed

    private void btnViewSavAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewSavAccActionPerformed
        // TODO add your handling code here:
        
        ViewSavingAccPanel viewsavaccpanel = new ViewSavingAccPanel(savings);
        splitPane.setRightComponent(viewsavaccpanel);
    }//GEN-LAST:event_btnViewSavAccActionPerformed

    private void btnCreateSavAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateSavAccActionPerformed
        // TODO add your handling code here:
        CreateSavingAccPanel createsavaccpanel = new CreateSavingAccPanel(savings);
        splitPane.setRightComponent(createsavaccpanel);
    }//GEN-LAST:event_btnCreateSavAccActionPerformed

    private void btnCreateAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAddActionPerformed
        // TODO add your handling code here:
        
        CreateAddPanel createaddpanel = new CreateAddPanel(address);
        splitPane.setRightComponent(createaddpanel);
                
    }//GEN-LAST:event_btnCreateAddActionPerformed

    private void btnCreateCheckAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateCheckAccActionPerformed
        // TODO add your handling code here:
        
        CreateCheckingAccPanel createcheckpanel = new CreateCheckingAccPanel(checking);
        splitPane.setRightComponent(createcheckpanel);
    }//GEN-LAST:event_btnCreateCheckAccActionPerformed

    private void btnViewCheckAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCheckAccActionPerformed
        // TODO add your handling code here:
        ViewCheckingAccPanel viewcheckpanel = new ViewCheckingAccPanel(checking);
        splitPane.setRightComponent(viewcheckpanel);
    }//GEN-LAST:event_btnViewCheckAccActionPerformed

    private void btnViewAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAddActionPerformed
        // TODO add your handling code here:
        
        ViewAddPanel viewaddpanel = new ViewAddPanel(address);
        splitPane.setRightComponent(viewaddpanel);
    }//GEN-LAST:event_btnViewAddActionPerformed

    private void btnViewLicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewLicActionPerformed
        // TODO add your handling code here:
        ViewLicensePanel viewlicpanel = new ViewLicensePanel(license);
        splitPane.setRightComponent(viewlicpanel);
    }//GEN-LAST:event_btnViewLicActionPerformed

    private void btnCreateLicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateLicActionPerformed
        // TODO add your handling code here:
        CreateLicensePanel createlicpanel = new CreateLicensePanel(license);
        splitPane.setRightComponent(createlicpanel);
    }//GEN-LAST:event_btnCreateLicActionPerformed

    private void btnViewReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewReportActionPerformed
        // TODO add your handling code here:
        ViewReport viewreport = new ViewReport(person, address, checking, savings, record, license);
        splitPane.setRightComponent(viewreport);
    }//GEN-LAST:event_btnViewReportActionPerformed

    private void btnCreateMedRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateMedRecActionPerformed
        // TODO add your handling code here:
        CreateMedRec createmedrec = new CreateMedRec(record);
        splitPane.setRightComponent(createmedrec);
    }//GEN-LAST:event_btnCreateMedRecActionPerformed

    private void btnViewMedRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewMedRecActionPerformed
        // TODO add your handling code here:
        ViewMedRec viewmedrec = new ViewMedRec(record);
        splitPane.setRightComponent(viewmedrec);
        
    }//GEN-LAST:event_btnViewMedRecActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateAdd;
    private javax.swing.JButton btnCreateCheckAcc;
    private javax.swing.JButton btnCreateLic;
    private javax.swing.JButton btnCreateMedRec;
    private javax.swing.JButton btnCreatePI;
    private javax.swing.JButton btnCreateSavAcc;
    private javax.swing.JButton btnViewAdd;
    private javax.swing.JButton btnViewCheckAcc;
    private javax.swing.JButton btnViewLic;
    private javax.swing.JButton btnViewMedRec;
    private javax.swing.JButton btnViewPI;
    private javax.swing.JButton btnViewReport;
    private javax.swing.JButton btnViewSavAcc;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel viewPanel;
    // End of variables declaration//GEN-END:variables
}
