/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.Address;
import model.CheckingAccount;
import model.License;
import model.MedicalRec;
import model.PersonalInfo;
import model.SavingsAccount;

/**
 *
 * @author 12013
 */
public class ViewReport extends javax.swing.JPanel {

    /**
     * Creates new form ViewReport
     */
    PersonalInfo person;
    Address address;
    CheckingAccount checking;
    SavingsAccount savings;
    MedicalRec record;
    License license;
    
    
    
    public ViewReport(PersonalInfo person, Address address, CheckingAccount checking, SavingsAccount savings,MedicalRec record, License license) {
        initComponents();
        this.person = person;
        this.address = address;
        this.checking = checking;
        this.savings = savings;
        this.record = record;
        this.license = license;
        
        displayReport();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblPhNum = new javax.swing.JLabel();
        txtFirst = new javax.swing.JTextField();
        lblDob = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        txtDOB = new javax.swing.JTextField();
        lblHt = new javax.swing.JLabel();
        txtPhNo = new javax.swing.JTextField();
        lblWt = new javax.swing.JLabel();
        txtHeight = new javax.swing.JTextField();
        lblSsn = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        txtSsn = new javax.swing.JTextField();
        txtWeight = new javax.swing.JTextField();
        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        txtLast = new javax.swing.JTextField();
        txtZipCode = new javax.swing.JTextField();
        txtState = new javax.swing.JTextField();
        lblstAdd = new javax.swing.JLabel();
        lblZipCode = new javax.swing.JLabel();
        lblcity = new javax.swing.JLabel();
        txtcity = new javax.swing.JTextField();
        lblstate = new javax.swing.JLabel();
        txtStreetAdd = new javax.swing.JTextField();
        lblSavAccBal1 = new javax.swing.JLabel();
        txtSavAccBal = new javax.swing.JTextField();
        lblSAccType1 = new javax.swing.JLabel();
        txtSavAccNo = new javax.swing.JTextField();
        txtSavAccType = new javax.swing.JTextField();
        lblSavRtNo1 = new javax.swing.JLabel();
        lblSavAccNo1 = new javax.swing.JLabel();
        txtSavRtNo = new javax.swing.JTextField();
        lnlSavBaName1 = new javax.swing.JLabel();
        txtSavBaName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lnlSavBaName2 = new javax.swing.JLabel();
        txtChkBaName = new javax.swing.JTextField();
        lblSavAccBal2 = new javax.swing.JLabel();
        txtChkAccBal = new javax.swing.JTextField();
        lblSAccType2 = new javax.swing.JLabel();
        txtChkAccNo = new javax.swing.JTextField();
        txtSavAccType2 = new javax.swing.JTextField();
        lblSavRtNo2 = new javax.swing.JLabel();
        lblSavAccNo2 = new javax.swing.JLabel();
        txtChkRtNo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtLicNum = new javax.swing.JTextField();
        txtLibBloodType = new javax.swing.JTextField();
        txtLicDOE = new javax.swing.JTextField();
        txtSavChkType = new javax.swing.JTextField();
        lblLicDOI = new javax.swing.JLabel();
        lblLicDOE = new javax.swing.JLabel();
        lblLicNum = new javax.swing.JLabel();
        lclLicBT = new javax.swing.JLabel();
        lblLicPic = new javax.swing.JLabel();
        txtLicDOI = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtAll1 = new javax.swing.JTextField();
        lblAll2 = new javax.swing.JLabel();
        txtMedRecNum = new javax.swing.JTextField();
        txtAll3 = new javax.swing.JTextField();
        txtAll2 = new javax.swing.JTextField();
        lblMedRedNum = new javax.swing.JLabel();
        lblAll3 = new javax.swing.JLabel();
        lblAll1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 204, 255));
        setAutoscrolls(true);

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 15)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("REPORT");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Demographic Information");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Address");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Savings Account");

        lblPhNum.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPhNum.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPhNum.setText("First Name :");

        txtFirst.setEditable(false);
        txtFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstActionPerformed(evt);
            }
        });

        lblDob.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDob.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblDob.setText("Date of Birth :");

        lblAge.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAge.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblAge.setText("Age :");

        txtDOB.setEditable(false);

        lblHt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblHt.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblHt.setText("SSN :");

        txtPhNo.setEditable(false);

        lblWt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblWt.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblWt.setText("Height :");

        txtHeight.setEditable(false);

        lblSsn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSsn.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblSsn.setText("Weight :");

        txtAge.setEditable(false);

        txtSsn.setEditable(false);

        txtWeight.setEditable(false);

        lblFirstName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFirstName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblFirstName.setText("Last Name :");

        lblLastName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblLastName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblLastName.setText("Phone Number :");

        txtLast.setEditable(false);
        txtLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastActionPerformed(evt);
            }
        });

        txtZipCode.setEditable(false);

        txtState.setEditable(false);

        lblstAdd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblstAdd.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblstAdd.setText("Street Address :");

        lblZipCode.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblZipCode.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblZipCode.setText("Zip Code :");

        lblcity.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblcity.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblcity.setText("City :");

        txtcity.setEditable(false);
        txtcity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcityActionPerformed(evt);
            }
        });

        lblstate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblstate.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblstate.setText("State :");

        txtStreetAdd.setEditable(false);

        lblSavAccBal1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSavAccBal1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblSavAccBal1.setText("Account Balance :");

        txtSavAccBal.setEditable(false);

        lblSAccType1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSAccType1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblSAccType1.setText("Account Type :");

        txtSavAccNo.setEditable(false);

        txtSavAccType.setEditable(false);
        txtSavAccType.setText("Savings");
        txtSavAccType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSavAccTypeActionPerformed(evt);
            }
        });

        lblSavRtNo1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSavRtNo1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblSavRtNo1.setText("Bank Routing Number :");

        lblSavAccNo1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSavAccNo1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblSavAccNo1.setText("Bank Account Number :");

        txtSavRtNo.setEditable(false);
        txtSavRtNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSavRtNoActionPerformed(evt);
            }
        });

        lnlSavBaName1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lnlSavBaName1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lnlSavBaName1.setText("Bank Name :");

        txtSavBaName.setEditable(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Checking Account");

        lnlSavBaName2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lnlSavBaName2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lnlSavBaName2.setText("Bank Name :");

        txtChkBaName.setEditable(false);

        lblSavAccBal2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSavAccBal2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblSavAccBal2.setText("Account Balance :");

        txtChkAccBal.setEditable(false);

        lblSAccType2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSAccType2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblSAccType2.setText("Account Type :");

        txtChkAccNo.setEditable(false);

        txtSavAccType2.setEditable(false);
        txtSavAccType2.setText("Checking");
        txtSavAccType2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSavAccType2ActionPerformed(evt);
            }
        });

        lblSavRtNo2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSavRtNo2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblSavRtNo2.setText("Bank Routing Number :");

        lblSavAccNo2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSavAccNo2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblSavAccNo2.setText("Bank Account Number :");

        txtChkRtNo.setEditable(false);
        txtChkRtNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChkRtNoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Driving License");

        txtLicNum.setEditable(false);

        txtLibBloodType.setEditable(false);

        txtLicDOE.setEditable(false);

        txtSavChkType.setEditable(false);
        txtSavChkType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSavChkTypeActionPerformed(evt);
            }
        });

        lblLicDOI.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblLicDOI.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblLicDOI.setText("Date of Issue :");

        lblLicDOE.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblLicDOE.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblLicDOE.setText("Expiration Date :");

        lblLicNum.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblLicNum.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblLicNum.setText("License Number :");

        lclLicBT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lclLicBT.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lclLicBT.setText("Blood Type :");

        lblLicPic.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblLicPic.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblLicPic.setText("Upload Picture :");

        txtLicDOI.setEditable(false);
        txtLicDOI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLicDOIActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Medical Record");

        txtAll1.setEditable(false);
        txtAll1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAll1ActionPerformed(evt);
            }
        });

        lblAll2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAll2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblAll2.setText("Allergy 2 :");

        txtMedRecNum.setEditable(false);

        txtAll3.setEditable(false);

        txtAll2.setEditable(false);

        lblMedRedNum.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMedRedNum.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblMedRedNum.setText("Medical Record Number :");

        lblAll3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAll3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblAll3.setText("Allergy 3 :");

        lblAll1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAll1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblAll1.setText("Allergy 1 :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1305, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 977, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 26, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(275, 275, 275)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(276, 276, 276)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDob, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAge, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblWt, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSsn, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPhNum, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLastName)
                            .addComponent(lblHt, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtLast, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                            .addComponent(txtPhNo, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                            .addComponent(txtDOB, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                            .addComponent(txtAge, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                            .addComponent(txtHeight, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                            .addComponent(txtWeight, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                            .addComponent(txtSsn, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                            .addComponent(txtFirst))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblcity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblstate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblstAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblZipCode, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcity, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStreetAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lnlSavBaName1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSavAccBal1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSAccType1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSavRtNo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSavAccNo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSavRtNo, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSavBaName, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSavAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSavAccBal, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSavAccType, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(316, 316, 316)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(224, 224, 224)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblSAccType2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSavAccBal2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSavAccNo2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtChkAccBal, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtChkAccNo)
                                    .addComponent(txtSavAccType2, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblSavRtNo2)
                                    .addComponent(lnlSavBaName2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtChkBaName, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                                    .addComponent(txtChkRtNo))))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblLicNum, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lclLicBT, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLicPic, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLicDOE, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLicDOI, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLicDOI, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLicDOE, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLibBloodType, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSavChkType, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLicNum, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAll1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAll2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAll3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMedRedNum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAll1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAll2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMedRecNum, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAll3, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 640, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 641, Short.MAX_VALUE)))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblAge, lblDob, lblFirstName, lblHt, lblSsn, lblWt});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtState, txtStreetAdd, txtZipCode, txtcity});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtLibBloodType, txtLicDOE, txtLicDOI, txtSavChkType});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtAll1, txtAll2, txtAll3, txtMedRecNum});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtSavAccBal, txtSavAccNo, txtSavAccType, txtSavBaName, txtSavRtNo});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblPhNum, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFirst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLast, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPhNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblDob, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblAge, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblWt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblstAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtStreetAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblcity, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblstate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtState, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSsn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHt, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSsn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lnlSavBaName1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txtSavBaName, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSavRtNo1)
                            .addComponent(txtSavRtNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSavAccNo1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSavAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSavAccBal1)
                            .addComponent(txtSavAccBal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSAccType1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSavAccType, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lnlSavBaName2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtChkBaName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtChkRtNo, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSavRtNo2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSavAccNo2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(txtChkAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtChkAccBal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSavAccBal2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSavAccType2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSAccType2))
                        .addGap(623, 623, 623))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLicNum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLicNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLicDOI)
                            .addComponent(txtLicDOI, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLicDOE, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLicDOE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLibBloodType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lclLicBT)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblLicPic, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSavChkType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMedRedNum, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMedRecNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAll1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAll1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAll2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAll2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAll3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtAll3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 613, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 614, Short.MAX_VALUE)))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtAll1, txtAll2, txtAll3, txtMedRecNum});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtLibBloodType, txtLicDOE, txtLicDOI, txtLicNum, txtSavChkType});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtChkAccBal, txtChkBaName, txtChkRtNo, txtSavAccType2});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtAge, txtDOB, txtFirst, txtHeight, txtLast, txtPhNo, txtSsn, txtWeight});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtState, txtStreetAdd, txtZipCode, txtcity});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtSavAccNo, txtSavAccType, txtSavBaName, txtSavRtNo});

    }// </editor-fold>//GEN-END:initComponents

    private void txtFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstActionPerformed

    private void txtLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastActionPerformed

    private void txtcityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcityActionPerformed

    private void txtSavAccTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSavAccTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSavAccTypeActionPerformed

    private void txtSavRtNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSavRtNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSavRtNoActionPerformed

    private void txtSavAccType2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSavAccType2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSavAccType2ActionPerformed

    private void txtChkRtNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChkRtNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChkRtNoActionPerformed

    private void txtSavChkTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSavChkTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSavChkTypeActionPerformed

    private void txtLicDOIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLicDOIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLicDOIActionPerformed

    private void txtAll1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAll1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAll1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblAll1;
    private javax.swing.JLabel lblAll2;
    private javax.swing.JLabel lblAll3;
    private javax.swing.JLabel lblDob;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblHt;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblLicDOE;
    private javax.swing.JLabel lblLicDOI;
    private javax.swing.JLabel lblLicNum;
    private javax.swing.JLabel lblLicPic;
    private javax.swing.JLabel lblMedRedNum;
    private javax.swing.JLabel lblPhNum;
    private javax.swing.JLabel lblSAccType1;
    private javax.swing.JLabel lblSAccType2;
    private javax.swing.JLabel lblSavAccBal1;
    private javax.swing.JLabel lblSavAccBal2;
    private javax.swing.JLabel lblSavAccNo1;
    private javax.swing.JLabel lblSavAccNo2;
    private javax.swing.JLabel lblSavRtNo1;
    private javax.swing.JLabel lblSavRtNo2;
    private javax.swing.JLabel lblSsn;
    private javax.swing.JLabel lblWt;
    private javax.swing.JLabel lblZipCode;
    private javax.swing.JLabel lblcity;
    private javax.swing.JLabel lblstAdd;
    private javax.swing.JLabel lblstate;
    private javax.swing.JLabel lclLicBT;
    private javax.swing.JLabel lnlSavBaName1;
    private javax.swing.JLabel lnlSavBaName2;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtAll1;
    private javax.swing.JTextField txtAll2;
    private javax.swing.JTextField txtAll3;
    private javax.swing.JTextField txtChkAccBal;
    private javax.swing.JTextField txtChkAccNo;
    private javax.swing.JTextField txtChkBaName;
    private javax.swing.JTextField txtChkRtNo;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtFirst;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtLast;
    private javax.swing.JTextField txtLibBloodType;
    private javax.swing.JTextField txtLicDOE;
    private javax.swing.JTextField txtLicDOI;
    private javax.swing.JTextField txtLicNum;
    private javax.swing.JTextField txtMedRecNum;
    private javax.swing.JTextField txtPhNo;
    private javax.swing.JTextField txtSavAccBal;
    private javax.swing.JTextField txtSavAccNo;
    private javax.swing.JTextField txtSavAccType;
    private javax.swing.JTextField txtSavAccType2;
    private javax.swing.JTextField txtSavBaName;
    private javax.swing.JTextField txtSavChkType;
    private javax.swing.JTextField txtSavRtNo;
    private javax.swing.JTextField txtSsn;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtStreetAdd;
    private javax.swing.JTextField txtWeight;
    private javax.swing.JTextField txtZipCode;
    private javax.swing.JTextField txtcity;
    // End of variables declaration//GEN-END:variables

    private void displayReport() {
        
        txtFirst.setText(person.getFirstName());
        txtLast.setText(person.getLastName());
        txtPhNo.setText(person.getPhoneNum());
        txtDOB.setText(person.getDateOfBirth());
        txtAge.setText(person.getAge());
        txtHeight.setText(person.getHeight());
        txtWeight.setText(person.getWeight());
        txtSsn.setText(person.getSsn());
       
        
        txtStreetAdd.setText(address.getStAdd());
        txtcity.setText(address.getCity());
        txtState.setText(address.getState());
        txtZipCode.setText(address.getZipCode());
        
        txtSavBaName.setText(savings.getBankName());
        txtSavRtNo.setText(savings.getBankRtNo());
        txtSavAccNo.setText(savings.getBankAcNo());
        txtSavAccBal.setText(savings.getAccBal());
        
        txtChkBaName.setText(checking.getChkBankName());
        txtChkRtNo.setText(checking.getChkBankRtNo());
        txtChkAccNo.setText(checking.getChkBankAcNo());
        txtChkAccBal.setText(checking.getChkAccBal());
        
        txtLicNum.setText(license.getLicNum());
        txtLicDOI.setText(license.getLicDOI());
        txtLicDOE.setText(license.getLicDOE());
        txtLibBloodType.setText(license.getLicBlTy());
        
        txtMedRecNum.setText(record.getMedRecNo());
        txtAll1.setText(record.getAllr1());
        txtAll2.setText(record.getAllr2());
        txtAll3.setText(record.getAllr3());
        
        
        
        
    }
    
}
