/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JOptionPane;
import model.MedicalRec;

/**
 *
 * @author 12013
 */
public class ViewMedRec extends javax.swing.JPanel {

    /**
     * Creates new form CreateAddPanel
     */
    MedicalRec record;
    
    public ViewMedRec(MedicalRec record) {
        initComponents();
        this.record = record;
        displayMedicalRecord();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAll1 = new javax.swing.JLabel();
        txtAll1 = new javax.swing.JTextField();
        lblAll2 = new javax.swing.JLabel();
        txtMedRecNum = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        txtAll3 = new javax.swing.JTextField();
        txtAll2 = new javax.swing.JTextField();
        lblMedRedNum = new javax.swing.JLabel();
        lblAll3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 51));
        setPreferredSize(new java.awt.Dimension(1000, 800));

        lblAll1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAll1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblAll1.setText("Allergy 1 :");

        txtAll1.setEditable(false);
        txtAll1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAll1ActionPerformed(evt);
            }
        });

        lblAll2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAll2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblAll2.setText("Allergy 2 :");

        txtMedRecNum.setEditable(false);

        lblTitle.setBackground(new java.awt.Color(255, 204, 204));
        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Medical Record Details");
        lblTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtAll3.setEditable(false);

        txtAll2.setEditable(false);

        lblMedRedNum.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMedRedNum.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblMedRedNum.setText("Medical Record Number :");

        lblAll3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAll3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblAll3.setText("Allergy 3 :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAll1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAll2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAll3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMedRedNum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAll3, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAll2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAll1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMedRecNum, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtAll1, txtAll2, txtAll3, txtMedRecNum});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMedRedNum, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMedRecNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAll1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAll1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAll2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAll2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAll3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAll3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(559, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtAll1, txtAll2, txtAll3, txtMedRecNum});

    }// </editor-fold>//GEN-END:initComponents

    private void txtAll1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAll1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAll1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAll1;
    private javax.swing.JLabel lblAll2;
    private javax.swing.JLabel lblAll3;
    private javax.swing.JLabel lblMedRedNum;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtAll1;
    private javax.swing.JTextField txtAll2;
    private javax.swing.JTextField txtAll3;
    private javax.swing.JTextField txtMedRecNum;
    // End of variables declaration//GEN-END:variables

    private void displayMedicalRecord() {
        txtMedRecNum.setText(record.getMedRecNo());
        txtAll1.setText(record.getAllr1());
        txtAll2.setText(record.getAllr2());
        txtAll3.setText(record.getAllr3());
        
    }
}
