/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.License;

/**
 *
 * @author 12013
 */
public class ViewLicensePanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPerInfoPanel
     */
    License license;
    
    public ViewLicensePanel(License license) {
        initComponents();
        
        this.license = license;
        displayLicenseInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtLicDOI = new javax.swing.JTextField();
        txtLicNum = new javax.swing.JTextField();
        txtLibBloodType = new javax.swing.JTextField();
        txtLicDOE = new javax.swing.JTextField();
        txtSavChkType = new javax.swing.JTextField();
        lblLicDOI = new javax.swing.JLabel();
        lblLicDOE = new javax.swing.JLabel();
        lblLicNum = new javax.swing.JLabel();
        lclLicBT = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblLicPic = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 102, 102));

        txtLicDOI.setEditable(false);
        txtLicDOI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLicDOIActionPerformed(evt);
            }
        });

        txtLicNum.setEditable(false);

        txtLibBloodType.setEditable(false);

        txtLicDOE.setEditable(false);

        txtSavChkType.setEditable(false);
        txtSavChkType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSavChkTypeActionPerformed(evt);
            }
        });

        lblLicDOI.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblLicDOI.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblLicDOI.setText("Date of Issue :");

        lblLicDOE.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblLicDOE.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblLicDOE.setText("Expiration Date :");

        lblLicNum.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblLicNum.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblLicNum.setText("License Number :");

        lclLicBT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lclLicBT.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lclLicBT.setText("Blood Type :");

        lblTitle.setBackground(new java.awt.Color(255, 204, 204));
        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Driver's License Information");

        lblLicPic.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblLicPic.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblLicPic.setText("Uploaded Picture :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(226, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLicNum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lclLicBT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLicPic, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLicDOI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLicDOE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLibBloodType, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLicDOE, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLicDOI, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLicNum, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSavChkType, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(227, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtLibBloodType, txtLicDOE, txtLicDOI, txtLicNum, txtSavChkType});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblLicDOE, lblLicDOI, lblLicNum, lblLicPic, lclLicBT});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLicNum, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLicNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLicDOI, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLicDOI, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLicDOE, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLicDOE, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lclLicBT)
                    .addComponent(txtLibBloodType, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLicPic, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSavChkType, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(202, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtLibBloodType, txtLicDOE, txtLicDOI, txtLicNum, txtSavChkType});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblLicDOE, lblLicDOI, lblLicNum, lblLicPic, lclLicBT});

    }// </editor-fold>//GEN-END:initComponents

    private void txtLicDOIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLicDOIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLicDOIActionPerformed

    private void txtSavChkTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSavChkTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSavChkTypeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblLicDOE;
    private javax.swing.JLabel lblLicDOI;
    private javax.swing.JLabel lblLicNum;
    private javax.swing.JLabel lblLicPic;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lclLicBT;
    private javax.swing.JTextField txtLibBloodType;
    private javax.swing.JTextField txtLicDOE;
    private javax.swing.JTextField txtLicDOI;
    private javax.swing.JTextField txtLicNum;
    private javax.swing.JTextField txtSavChkType;
    // End of variables declaration//GEN-END:variables

 


    private void displayLicenseInfo() {
        
        txtLicNum.setText(license.getLicNum());
        txtLicDOI.setText(license.getLicDOI());
        txtLicDOE.setText(license.getLicDOE());
        txtLibBloodType.setText(license.getLicBlTy());
        //txtLicNum.setText(license.getLicNum());
    }
}
