/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.CheckingAccount;

/**
 *
 * @author 12013
 */
public class ViewCheckingAccPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPerInfoPanel
     */
    CheckingAccount checking;
    
    public ViewCheckingAccPanel(CheckingAccount checking) {
        initComponents();
        
        this.checking = checking;
        displayCheckingAccInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        txtSavAccType = new javax.swing.JTextField();
        lblSavRtNo = new javax.swing.JLabel();
        lblSavAccNo = new javax.swing.JLabel();
        txtChkRtNo = new javax.swing.JTextField();
        lnlSavBaName = new javax.swing.JLabel();
        txtChkBaName = new javax.swing.JTextField();
        lblSavAccBal = new javax.swing.JLabel();
        txtChkAccBal = new javax.swing.JTextField();
        lblSAccType = new javax.swing.JLabel();
        txtChkAccNo = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 204));

        lblTitle.setBackground(new java.awt.Color(255, 204, 204));
        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Checking Account Details");
        lblTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtSavAccType.setEditable(false);
        txtSavAccType.setText("Checking");
        txtSavAccType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSavAccTypeActionPerformed(evt);
            }
        });

        lblSavRtNo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSavRtNo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblSavRtNo.setText("Bank Routing Number :");

        lblSavAccNo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSavAccNo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblSavAccNo.setText("Bank Account Number :");

        txtChkRtNo.setEditable(false);
        txtChkRtNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChkRtNoActionPerformed(evt);
            }
        });

        lnlSavBaName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lnlSavBaName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lnlSavBaName.setText("Bank Name :");

        txtChkBaName.setEditable(false);

        lblSavAccBal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSavAccBal.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblSavAccBal.setText("Account Balance :");

        txtChkAccBal.setEditable(false);

        lblSAccType.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSAccType.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblSAccType.setText("Account Type :");

        txtChkAccNo.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 869, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lnlSavBaName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSavAccBal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSAccType, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSavRtNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSavAccNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtChkAccBal, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtChkAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtChkRtNo, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtChkBaName, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSavAccType, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtChkAccBal, txtChkAccNo, txtChkBaName, txtChkRtNo, txtSavAccType});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblSAccType, lblSavAccBal, lblSavAccNo, lblSavRtNo, lnlSavBaName});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lnlSavBaName, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtChkBaName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSavRtNo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtChkRtNo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSavAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtChkAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSavAccBal)
                    .addComponent(txtChkAccBal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSAccType, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSavAccType, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(238, 238, 238))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtChkAccBal, txtChkAccNo, txtChkBaName, txtChkRtNo, txtSavAccType});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblSAccType, lblSavAccBal, lblSavAccNo, lblSavRtNo, lnlSavBaName});

    }// </editor-fold>//GEN-END:initComponents

    private void txtSavAccTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSavAccTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSavAccTypeActionPerformed

    private void txtChkRtNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChkRtNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChkRtNoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblSAccType;
    private javax.swing.JLabel lblSavAccBal;
    private javax.swing.JLabel lblSavAccNo;
    private javax.swing.JLabel lblSavRtNo;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lnlSavBaName;
    private javax.swing.JTextField txtChkAccBal;
    private javax.swing.JTextField txtChkAccNo;
    private javax.swing.JTextField txtChkBaName;
    private javax.swing.JTextField txtChkRtNo;
    private javax.swing.JTextField txtSavAccType;
    // End of variables declaration//GEN-END:variables

 


    private void displayCheckingAccInfo() {
        txtChkBaName.setText(checking.getChkBankName());
        txtChkRtNo.setText(checking.getChkBankRtNo());
        txtChkAccNo.setText(checking.getChkBankAcNo());
        txtChkAccBal.setText(checking.getChkAccBal());
        
    }
}
