package LoginUI;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import AdminUI.AdminInfo;
import java.awt.CardLayout;
import javax.swing.JPanel;

import StudentUI.StudentInfo;
import info5100.university.example.Department.Department;
import info5100.university.example.Persona.StudentProfile;

/**
 *
 * @author snehaswaroop
 */
public class LoginScreen extends javax.swing.JPanel {

    /**
     * Creates new form LoginScreen
     */
    JPanel mainWorkArea;
    Department department;
    StudentProfile selectedID = null;

    public LoginScreen(JPanel mainWorkArea, Department d) {
        initComponents();

        this.mainWorkArea = mainWorkArea;
        this.department = d;
        lblStudentID.setVisible(false);
        txtStudentID.setVisible(false);
        populateRoleCombo();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRole = new javax.swing.JLabel();
        cmbRoles = new javax.swing.JComboBox<>();
        lblStudentID = new javax.swing.JLabel();
        txtStudentID = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        warningForValidId = new javax.swing.JLabel();

        lblRole.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRole.setText("Choose Roles");

        cmbRoles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Student" }));
        cmbRoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRolesActionPerformed(evt);
            }
        });

        lblStudentID.setText("Enter Student Id");

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRole, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbRoles, 0, 136, Short.MAX_VALUE)
                            .addComponent(txtStudentID)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(btnLogin)))
                .addContainerGap(113, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(warningForValidId)
                .addGap(182, 182, 182))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblRole)
                    .addComponent(cmbRoles, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudentID)
                    .addComponent(txtStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(warningForValidId)
                .addGap(36, 36, 36)
                .addComponent(btnLogin)
                .addContainerGap(142, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:

        JPanel selectedPanel = (JPanel) cmbRoles.getSelectedItem();

        if (selectedPanel.getClass() == StudentInfo.class) {
            selectedID = department.getStudentDirectory().findStudent(txtStudentID.getText());
            if (selectedID != null) {
                warningForValidId.setText("");
                selectedPanel = new StudentInfo(mainWorkArea, department, selectedID);
                txtStudentID.setText("");
                mainWorkArea.add("WordAreaPanel", selectedPanel);
                CardLayout layout = (CardLayout) mainWorkArea.getLayout();
                layout.next(mainWorkArea);
            } else {
                txtStudentID.setText("");
                warningForValidId.setText("Please enter valid student Id");
                
            }
        } else if (selectedPanel.getClass() == AdminInfo.class) {
            warningForValidId.setText("");
            selectedPanel = new AdminInfo(mainWorkArea, department);
            mainWorkArea.add("WordAreaPanel", selectedPanel);
            CardLayout layout = (CardLayout) mainWorkArea.getLayout();
            layout.next(mainWorkArea);
        }


    }//GEN-LAST:event_btnLoginActionPerformed

    private void cmbRolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRolesActionPerformed
        // TODO add your handling code here:
        updateRolesVisibility();
    }//GEN-LAST:event_cmbRolesActionPerformed

    public void populateRoleCombo() {

        cmbRoles.removeAllItems();
        AdminInfo admin = new AdminInfo(mainWorkArea, department);
        StudentInfo student = new StudentInfo(mainWorkArea, department, selectedID);

        cmbRoles.addItem(admin);
        cmbRoles.addItem(student);

    }

    public void populateStudentBox() {

        lblStudentID.setText("Enter Student ID");
        txtStudentID.setVisible(true);

    }

    private void updateRolesVisibility() {
        
        warningForValidId.setText("");
        if ((cmbRoles.getSelectedItem() == null) || (cmbRoles.getSelectedItem().getClass() == AdminInfo.class)) {
            selectedID = null;
            lblStudentID.setVisible(false);
            txtStudentID.setVisible(false);
            return;
        } else {
            lblStudentID.setVisible(true);
            lblStudentID.setText("Enter Student ID");
            txtStudentID.setVisible(true);
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JComboBox<Object> cmbRoles;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblStudentID;
    private javax.swing.JTextField txtStudentID;
    private javax.swing.JLabel warningForValidId;
    // End of variables declaration//GEN-END:variables
}
