/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AdminUI;


import javax.swing.JPanel;
import info5100.university.example.Department.Department;
import java.awt.CardLayout;
import java.awt.Component;
import LoginUI.LoginScreen;



public class AdminInfo extends javax.swing.JPanel {

    /**
     * Creates new form AdminInfo
     */
    
    JPanel mainWorkArea;
    Department department;
    
    public AdminInfo(JPanel mainWorkArea, Department d) {
        initComponents();
        
        this.mainWorkArea = mainWorkArea;
        this.department = d;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        controlPanel = new javax.swing.JPanel();
        btnCourseRankings = new javax.swing.JButton();
        btnAnalysis = new javax.swing.JButton();
        btnStuDetails = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        workArea = new javax.swing.JPanel();

        btnCourseRankings.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnCourseRankings.setText("Course Rankings");
        btnCourseRankings.setToolTipText("Click to view Course Rankings");
        btnCourseRankings.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCourseRankings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseRankingsActionPerformed(evt);
            }
        });

        btnAnalysis.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnAnalysis.setText("Analysis");
        btnAnalysis.setToolTipText("Click to view analysis");
        btnAnalysis.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAnalysis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalysisActionPerformed(evt);
            }
        });

        btnStuDetails.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnStuDetails.setText("Student Details");
        btnStuDetails.setToolTipText("Click to view Details of all students");
        btnStuDetails.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnStuDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStuDetailsActionPerformed(evt);
            }
        });

        btnLogOut.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnLogOut.setText("Log Out");
        btnLogOut.setToolTipText("Click to view Course Rankings");
        btnLogOut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCourseRankings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnalysis, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStuDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        controlPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAnalysis, btnCourseRankings, btnLogOut, btnStuDetails});

        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(btnStuDetails)
                .addGap(18, 18, 18)
                .addComponent(btnAnalysis)
                .addGap(13, 13, 13)
                .addComponent(btnCourseRankings)
                .addGap(18, 18, 18)
                .addComponent(btnLogOut)
                .addContainerGap(217, Short.MAX_VALUE))
        );

        splitPane.setLeftComponent(controlPanel);

        javax.swing.GroupLayout workAreaLayout = new javax.swing.GroupLayout(workArea);
        workArea.setLayout(workAreaLayout);
        workAreaLayout.setHorizontalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 485, Short.MAX_VALUE)
        );
        workAreaLayout.setVerticalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 392, Short.MAX_VALUE)
        );

        splitPane.setRightComponent(workArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnStuDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStuDetailsActionPerformed
        // TODO add your handling code here:
        DepartmentDetails createstudentdetPanel = new DepartmentDetails(department);
        splitPane.setRightComponent(createstudentdetPanel);
    }//GEN-LAST:event_btnStuDetailsActionPerformed

    private void btnAnalysisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalysisActionPerformed
        // TODO add your handling code here:
        Analysis createanalysispan = new Analysis(department);
        splitPane.setRightComponent(createanalysispan);
    }//GEN-LAST:event_btnAnalysisActionPerformed

    private void btnCourseRankingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseRankingsActionPerformed
        // TODO add your handling code here:
        CourseRankings courserankingpanel = new CourseRankings(department);
        splitPane.setRightComponent(courserankingpanel);
    }//GEN-LAST:event_btnCourseRankingsActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        mainWorkArea.remove(this);
        Component[] componentArray = mainWorkArea.getComponents();
        Component component = componentArray[0];
        LoginScreen loginPanel = (LoginScreen) component;
        loginPanel.populateRoleCombo();
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.previous(mainWorkArea);
        
    }//GEN-LAST:event_btnLogOutActionPerformed


    @Override
    public String toString(){
        return "Admin";
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalysis;
    private javax.swing.JButton btnCourseRankings;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnStuDetails;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}
